{
 "title": "Express JS Sample API",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_start_time_seconds", "legendFormat": "__auto" }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "{{__name__}}" },
    {
     "expr": "process_cpu_system_seconds_total",
     "legendFormat": "{{__name__}}"
    },
    { "expr": "process_cpu_user_seconds_total", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Memory consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{__name__}}" }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Active Handles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "nodejs_active_handles", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Active Resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "nodejs_active_resources", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "nodejs_active_requests", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    { "expr": "nodejs_heap_size_total_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}