global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

scrape_configs:
  - job_name: 'express.js-sample-api'
    static_configs:
      - targets: ['host.docker.internal:3000']
        labels:
          environment: 'sandbox'